import {seedRecruitedRoster} from './recruited-browser-fixture.mjs';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {botInput} from './bot.js';
const BASE=process.env.LUNARIA_URL||'http://127.0.0.1:5174';
const browser=await chromium.launch({channel:'chrome',headless:true});
const errors=[],checks=[],consoleErrors=[];
const check=(name,details={})=>{checks.push({name,status:'passed',...details});console.log(`PASS ${name}`,JSON.stringify(details));};
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});
await seedRecruitedRoster(context);
const page=await context.newPage();
function watch(page){page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')consoleErrors.push(e.text());});page.on('response',r=>{if(r.status()>=400)errors.push(`HTTP ${r.status()} ${r.url()}`);});}
watch(page);
try{
await page.goto(BASE);await page.waitForSelector('#loading',{state:'detached',timeout:30000});
assert.equal(await page.locator('#start').isVisible(),true);check('Cold boot and assets');
await page.screenshot({path:'audit/desktop-title.png'});
await page.click('[data-open="guide"] >> nth=0');assert.equal(await page.locator('#modal').getAttribute('open'),'');await page.keyboard.press('Escape');assert.equal(await page.locator('#modal').isVisible(),false);check('Guide opens, Escape closes');
await page.click('[data-open="settings"]');await page.uncheck('#setting-sound');await page.uncheck('#setting-music');await page.uncheck('#setting-motion');await page.selectOption('#setting-quality','low');await page.click('#modal [data-close] >> nth=0');
await page.reload();await page.waitForSelector('#loading',{state:'detached'});await page.click('[data-open="settings"]');assert.equal(await page.locator('#setting-sound').isChecked(),false);assert.equal(await page.locator('#setting-music').isChecked(),false);assert.equal(await page.locator('#setting-motion').isChecked(),false);assert.equal(await page.locator('#setting-quality').inputValue(),'low');await page.selectOption('#setting-quality','high');await page.click('#modal [data-close] >> nth=0');check('Settings persist across reload; quality can change');
await page.click('#difficulty');await page.click('[data-difficulty="hard"]');assert.match(await page.locator('#difficulty').innerText(),/チャレンジモード/);await page.click('#difficulty');await page.click('[data-difficulty="normal"]');check('Both difficulties selectable');
await page.click('[data-hero="1"]');await page.click('#start');await page.click('#story-skip');assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.player.hero),1);check('Selected hero leads the party');
const before=await page.evaluate(()=>window.__LUNARIA_TEST__.state.player);await page.keyboard.down('KeyW');await page.waitForTimeout(450);await page.keyboard.up('KeyW');const after=await page.evaluate(()=>window.__LUNARIA_TEST__.state.player);assert.ok(Math.hypot(after.x-before.x,after.z-before.z)>1);check('Keyboard movement follows screen direction');
await page.keyboard.press('Space');assert.ok((await page.evaluate(()=>window.__LUNARIA_TEST__.state.player)).dashCooldown>0);await page.keyboard.press('KeyQ');assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.player.hero),0);check('Keyboard dash and hero swap');
await page.keyboard.press('Escape');const paused=await page.evaluate(()=>window.__LUNARIA_TEST__.state.time);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.time),paused);assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.phase),'paused');await page.click('#resume');assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.phase),'playing');check('Pause freezes the simulation and resumes');
await page.evaluate(()=>{const t=window.__LUNARIA_TEST__;t.game.addCrystals(t.game.crystalGoal);t.step(.02);});assert.equal(await page.locator('[data-skill]').count(),3);const id=await page.locator('[data-skill]').first().getAttribute('data-skill');await page.screenshot({path:'audit/desktop-upgrade.png'});await page.locator('[data-skill]').first().click();assert.equal(await page.evaluate(id=>window.__LUNARIA_TEST__.state.skills[id],id),1);check('Level-up pauses and applies selected skill');
await page.evaluate(()=>window.__LUNARIA_TEST__.game.player.charge=100);await page.keyboard.press('KeyE');assert.ok(await page.evaluate(()=>window.__LUNARIA_TEST__.state.player.charge<100));check('Ultimate spends charge and triggers animation');
await page.waitForTimeout(1800);await page.screenshot({path:'audit/desktop-game.png'});
await page.evaluate(()=>{const t=window.__LUNARIA_TEST__;t.game.player.invincible=0;t.game.hurt(999,0,0);t.step(0);});assert.equal(await page.locator('.result.defeat').isVisible(),true);assert.match(await page.locator('.reward').innerText(),/経験値を保存/);await page.click('#retry');await page.click('#story-skip');assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.phase),'playing');assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.player.hp),await page.evaluate(()=>window.__LUNARIA_TEST__.state.player.maxHp));check('Defeat, saved result and retry');
// Follow the same decision policy used by the pure simulation tests. No HP, damage or enemy mutations.
await page.evaluate(source=>{window.__auditBot=eval(`(${source})`);},botInput.toString());
let iterations=0,chosen=0,bossCaptured=false;
while(iterations++<300){
 if(await page.locator('#story-dialog').isVisible())await page.click('#story-skip');
 const state=await page.evaluate(()=>{const t=window.__LUNARIA_TEST__;for(let i=0;i<60&&t.game.phase==='playing';i++)t.game.tick(1/60,window.__auditBot(t.game));t.step(0);return t.state;});
 if(state.phase==='upgrade'){const order=['orbit','power','haste','nova','crit','vitality','ward','echo','focus','leech','reach','stride'];const pick=[...state.offers].sort((a,b)=>order.indexOf(a)-order.indexOf(b))[0];await page.click(`[data-skill="${pick}"]`);chosen++;}
 if(state.wave===6&&!bossCaptured){await page.waitForTimeout(100);await page.screenshot({path:'audit/desktop-boss.png'});bossCaptured=true;}
 if(state.phase==='victory'||state.phase==='defeat')break;
 await page.waitForTimeout(15);
}
assert.equal(await page.evaluate(()=>window.__LUNARIA_TEST__.state.phase),'victory');assert.ok(chosen>=4);await page.click('#story-skip');assert.equal(await page.locator('.chapter-complete').isVisible(),true);await page.screenshot({path:'audit/desktop-victory.png'});check('Entire rendered campaign clears through all waves and skill dialogs',{iterations,chosen,state:await page.evaluate(()=>window.__LUNARIA_TEST__.state)});
await page.click('#menu-title');await page.click('[data-open="records"]');assert.match(await page.locator('.record-feature strong').innerText(),/[1-9]/);await page.click('#modal [data-close] >> nth=0');await page.reload();await page.waitForSelector('#loading',{state:'detached'});const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('lunaria-record-v1')));assert.ok(saved.wins>=1);assert.ok(saved.runs>=2);check('Campaign records persist across reload',{record:saved});
await page.click('#start');await page.click('#story-skip');const perf=await page.evaluate(async()=>{const deltas=[];let last=performance.now();for(let i=0;i<90;i++)await new Promise(resolve=>requestAnimationFrame(now=>{deltas.push(now-last);last=now;resolve();}));deltas.sort((a,b)=>a-b);return {medianFrameMs:deltas[45],p95FrameMs:deltas[85],gpu:window.__LUNARIA_TEST__.stats};});check('Performance sampled on local headless Chrome',perf);
let geometrySamples=[];for(let i=0;i<8;i++){await page.evaluate(()=>{const t=window.__LUNARIA_TEST__;t.home();t.start();t.step(2);});await page.waitForTimeout(120);await page.evaluate(()=>window.__LUNARIA_TEST__.home());await page.evaluate(()=>window.__LUNARIA_TEST__.world.render(null,.016));geometrySamples.push(await page.evaluate(()=>window.__LUNARIA_TEST__.stats.geometries));}
assert.ok(Math.max(...geometrySamples.slice(-4))-Math.min(...geometrySamples.slice(-4))<15);check('Eight run restarts release transient GPU geometry',{geometrySamples});
await context.close();
const mobileContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});await seedRecruitedRoster(mobileContext);const mobile=await mobileContext.newPage();watch(mobile);await mobile.goto(BASE);await mobile.waitForSelector('#loading',{state:'detached'});await mobile.screenshot({path:'audit/mobile-title.png'});
for(const size of [{width:390,height:844},{width:320,height:568},{width:844,height:390}]){await mobile.setViewportSize(size);const layout=await mobile.evaluate(()=>{const b=document.querySelector('#start').getBoundingClientRect();return {overflow:document.body.scrollWidth>innerWidth,startVisible:b.left>=0&&b.right<=innerWidth&&b.top>=0&&b.bottom<=innerHeight};});assert.equal(layout.overflow,false);assert.equal(layout.startVisible,true);check(`Responsive title ${size.width} × ${size.height}`,layout);}
await mobile.setViewportSize({width:390,height:844});await mobile.click('#start');await mobile.click('#story-skip');const initial=await mobile.evaluate(()=>window.__LUNARIA_TEST__.state.player);const session=await mobileContext.newCDPSession(mobile);
await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:70,y:620,id:1}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:124,y:620,id:1}]});await mobile.waitForTimeout(350);
const dashBox=await mobile.locator('#dash').boundingBox();const dx=dashBox.x+dashBox.width/2,dy=dashBox.y+dashBox.height/2;
await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:124,y:620,id:1},{x:dx,y:dy,id:2}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[{x:124,y:620,id:1}]});await mobile.waitForTimeout(100);
assert.ok(await mobile.evaluate(()=>window.__LUNARIA_TEST__.state.player.dashCooldown>0));await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const moved=await mobile.evaluate(()=>window.__LUNARIA_TEST__.state.player);assert.ok(Math.hypot(moved.x-initial.x,moved.z-initial.z)>1);assert.equal(await mobile.locator('#joystick').isVisible(),false);check('Mobile real multitouch movement and concurrent dash');
await mobile.click('#switch');assert.equal(await mobile.evaluate(()=>window.__LUNARIA_TEST__.state.player.hero),1);await mobile.waitForTimeout(3300);await mobile.screenshot({path:'audit/mobile-game.png'});await mobile.evaluate(()=>{const t=window.__LUNARIA_TEST__;t.game.addCrystals(t.game.crystalGoal);t.step(.02);});await mobile.screenshot({path:'audit/mobile-upgrade.png'});assert.equal(await mobile.locator('[data-skill]').count(),3);await mobile.locator('[data-skill]').first().tap();assert.equal(await mobile.evaluate(()=>window.__LUNARIA_TEST__.state.phase),'playing');check('Mobile swap and skill selection');
await mobile.click('#pause');await mobile.click('#quit');await mobileContext.close();
// Storage access can be denied in embedded/private contexts; gameplay must still boot.
const blocked=await browser.newContext({viewport:{width:1000,height:720}});await blocked.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new DOMException('blocked','SecurityError');};Storage.prototype.setItem=()=>{throw new DOMException('quota','QuotaExceededError');};});const p=await blocked.newPage();watch(p);await p.goto(BASE);await p.waitForSelector('#loading',{state:'detached'});await p.click('#start');await p.click('#story-skip');if(await p.locator('#battle-tutorial').isVisible())await p.click('#tutorial-skip');await p.evaluate(()=>{const t=window.__LUNARIA_TEST__;t.game.player.invincible=0;t.game.hurt(999,0,0);t.step(0);});assert.match(await p.locator('.reward').innerText(),/保存できません/);check('Unavailable local storage does not block play or results');await blocked.close();
assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);check('No uncaught JavaScript, WebGL shader, asset or console errors');
await writeFile('audit/browser-report.json',JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),base:BASE,checks,errors,consoleErrors},null,2));
console.log(`Audit finished: ${checks.length} checks passed.`);
}catch(e){await writeFile('audit/browser-report.json',JSON.stringify({date:new Date().toISOString(),checks,errors,consoleErrors,failure:e.stack},null,2));throw e;}finally{await browser.close();}
