import {RecruitedAdventure} from './recruited-fixture.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {STAGE_EXIT,ARENA_RADIUS} from '../src/model.js';
const tick=(g,n=1,input)=>{for(let i=0;i<n;i++)g.tick(1/60,input);};
function clearedWave(wave){const g=new RecruitedAdventure({seed:31});g.wave=wave;g.area=Math.floor((wave-1)/2);g.waveGoal=g.waveSpawned=wave===6?1:14;g.enemies=[];g.drainEvents();return g;}
test('the gate is physically inside the walking boundary and cannot skip a fight',()=>{const g=new RecruitedAdventure();Object.assign(g.player,g.exitPoint);assert.ok(Math.hypot(STAGE_EXIT.x,STAGE_EXIT.z)+STAGE_EXIT.radius<ARENA_RADIUS);assert.equal(g.crossExit(),false);assert.equal(g.wave,1);});
test('a cleared field waits indefinitely for the player and removes lingering danger',()=>{const g=clearedWave(2);g.projectiles=[{owner:'enemy',x:10,z:10,vx:0,vz:0,life:10,damage:2,radius:.4}];g.hazards=[{timer:100,total:100,x:0,z:0,radius:3}];tick(g);assert.equal(g.exitOpen,true);assert.equal(g.projectiles.length,0);assert.equal(g.hazards.length,0);tick(g,600);assert.equal(g.wave,2);assert.equal(g.phase,'playing');assert.equal(g.hurt(999,0,0),false);assert.equal(g.drainEvents().filter(e=>e.type==='exitOpen').length,1);});
test('entering a cleared gate advances exactly one stage and retains blessings while carrying HP',()=>{const g=clearedWave(2);g.player.hp=75;g.skills.power=2;tick(g,50);Object.assign(g.player,{x:g.exitPoint.x,z:g.exitPoint.z});tick(g);assert.equal(g.phase,'transition');assert.equal(g.stagesCleared,1);assert.equal(g.crossExit(),false);const stopped=g.snapshot();tick(g,60,{x:1,z:0});assert.deepEqual(g.snapshot(),stopped);assert.equal(g.advanceStage(),true);assert.equal(g.wave,3);assert.equal(g.area,1);assert.equal(g.player.hp,97);assert.equal(g.rank('power'),2);assert.equal(g.exitOpen,false);assert.equal(g.advanceStage(),false);assert.equal(g.player.z,8);});
test('gate collection resolves all crystal blessings before accepting an exit',()=>{const g=clearedWave(4);g.orbs=[{id:3,x:17,z:0,age:0,value:30}];tick(g);assert.equal(g.exitOpen,true);assert.equal(g.phase,'upgrade');Object.assign(g.player,{x:g.exitPoint.x,z:g.exitPoint.z});assert.equal(g.crossExit(),false);while(g.phase==='upgrade')g.chooseSkill(g.offers[0].id);tick(g,50);assert.equal(g.phase,'transition');assert.equal(g.stagesCleared,2);});
test('defeating the final guardian opens the gate without awarding victory',()=>{const g=clearedWave(6);const boss=g.spawnEnemy('boss',0,-10);g.hit(boss,9999,0,0);assert.equal(g.phase,'playing');tick(g,50);assert.equal(g.exitOpen,true);assert.equal(g.drainEvents().some(e=>e.type==='victory'),false);Object.assign(g.player,{x:g.exitPoint.x,z:g.exitPoint.z});tick(g);assert.equal(g.phase,'victory');assert.equal(g.stagesCleared,3);assert.equal(g.drainEvents().filter(e=>e.type==='victory').length,1);assert.equal(g.crossExit(),false);assert.equal(g.advanceStage(),false);});
test('pause freezes an armed gate and switching still works before crossing it',()=>{const g=clearedWave(2);tick(g);assert.equal(g.switchHero(),true);g.pause();const snap=g.snapshot();tick(g,90,{x:0,z:-1});assert.deepEqual(g.snapshot(),snap);g.resume();tick(g,50);assert.equal(g.exitOpen,true);});
