import {isHeroUnlocked,recruitmentNote} from './recruitment.js';
import {icon} from './icons.js';
import {skillsForParty,blessingSource,partyTitle} from './blessings.js';
import {PARTY_LIMIT} from './party.js';

export function partyView(party,lead,roster,levelFor,profile){
  const pool=skillsForParty(party,profile);
  return `<div class="modal-heading party-heading"><span class="eyebrow">ADVENTURE PARTY</span><h2>誰と冒険に出る？</h2><p>${isHeroUnlocked(profile,'tsukineko')?'1体でも、ふたりでも。出撃する仲間で祝福の候補が変わります。':'最初はにゃんるな一人で出発。つきねこは第1章の最後に共闘し、クリア後に正式加入します。'}</p></div>
  <div class="party-capacity"><strong>出撃メンバー</strong><span><b>${party.length}</b> / ${PARTY_LIMIT}体</span></div>
  <div class="party-roster">${roster.map((hero,i)=>{const unlocked=isHeroUnlocked(profile,hero.id),included=party.includes(hero.id),isLead=lead===i;return `<article class="party-member ${included?'included':!unlocked?'unrecruited':''}"><span class="portrait ${hero.id}" role="img" aria-label="${hero.name}"></span><div class="party-member-name"><strong>${hero.name}</strong><small>Lv.${levelFor(hero.id)} · ${hero.role}</small><span>${!unlocked?recruitmentNote(hero.id):included?(isLead?'先頭で出撃':'援護で出撃'):'待機中'}</span></div><div class="party-member-actions"><button data-party-toggle="${hero.id}" aria-pressed="${included}" aria-label="${hero.name}を${included?'編成から外す':'編成に加える'}" ${!unlocked||included&&party.length===1||!included&&party.length>=PARTY_LIMIT?'disabled':''}>${icon(included?'check':'link')}${!unlocked?'未加入':included?'外す':'連れて行く'}</button>${included?`<button data-party-lead="${i}" aria-pressed="${isLead}" ${isLead?'disabled':''}>${isLead?'先頭':'先頭にする'}</button>`:''}</div></article>`;}).join('')}</div>
  <section class="party-blessings" aria-label="この編成の祝福"><div class="party-blessings-title"><span>${icon(party.length===2?'link':'star')} この編成の祝福</span><b>${pool.length}種類</b></div><strong>${partyTitle(party,roster)}</strong><p>${party.length===2?'共通＋ふたりそれぞれの祝福＋連携の祝福。':'共通＋出撃キャラの祝福。単独出撃では援護・交代は使いません。'}<br>クリスタルを集めると、この候補から3択。対象キャラが指定された効果を除き、出撃メンバーで共有します。にゃんるなの必殺技・星屑・周回星は威力1.5倍。</p><div class="party-blessing-list">${pool.map(skill=>`<span data-party-blessing="${skill.id}" data-source="${skill.requires?.length===2?'pair':skill.requires?.[0]??'common'}" title="${blessingSource(skill,roster)}：${skill.text}">${icon(skill.icon)}${skill.name}<small>${blessingSource(skill,roster)}</small></span>`).join('')}</div><button class="skill-loadout-link" data-open-skill-loadout>スキル候補を付け替える ${icon('arrow')}</button></section>
  <p class="party-save-note" role="status">HPはキャラ別。援護中の仲間は無敵。倒れると生存中の相方へ自動交代し、全員倒れると終了します。<br>編成は自動保存。冒険中はメンバーを変更できません。</p><button class="primary" data-close>この編成で準備する ${icon('arrow')}</button>`;
}
