import {isHeroUnlocked,recruitmentNote} from './recruitment.js';
import {HEROES,AREAS} from './model.js';
import {ACTS,actLabel} from './acts.js';
import {STAGE_MISSIONS,missionsFor,missionsForAct,missionIndex,trialStatus} from './missions.js';
import {UNIQUE_EQUIPMENT,equipmentImage,uniqueEquipment,equipmentOwner,equipmentBonuses,equipmentBonusText} from './equipment.js';
import {resourceLabel} from './talents.js';
import {combatStats} from './progression.js';
import {icon} from './icons.js';
import {WEAPON_CATALOG,equippedWeapon,weaponImage} from './weapons.js';
import {weaponRarityBadge,weaponBonusText,weaponLoadoutView} from './weapons-ui.js';

export function missionRewardText(mission){return [...Object.entries(mission.rewards).map(([id,n])=>`${resourceLabel(id)} ×${n}`),...(mission.equipment?[uniqueEquipment(mission.equipment).name]:[])].join(' ／ ');}
function missionRow(profile,mission,game){
  const claimed=profile.missions.claimed.includes(mission.id),value=profile.missions.stages[missionIndex(mission.act,mission.area)][mission.metric],trial=game&&mission.act===game.act&&mission.area===game.area?trialStatus(mission,game):null;
  return `<article class="mission-row ${claimed?'claimed':''} ${mission.trial?'challenge-mission':''}" data-mission="${mission.id}"><span class="mission-status">${icon(claimed?'check':mission.trial?'trophy':'compass')}</span><div><div class="mission-name"><h4>${mission.name}</h4>${mission.trial?'<span>高難度</span>':''}</div><p>${mission.description}</p>${!claimed&&trial?`<small class="trial-live ${trial.eligible?'eligible':'failed'}">${trial.hard?'チャレンジモード':'チャレンジモードが必要'} · ${trial.seconds.toFixed(1)} / ${mission.trial.seconds}秒 · 被弾 ${trial.hits} / ${mission.trial.hits}回${trial.eligible?' · 達成圏内':' · この挑戦は条件未達'}</small>`:''}<div class="mission-reward">${icon(mission.equipment?'star':mission.rewards.limitStone?'crystal':'spark')}${missionRewardText(mission)}</div><div class="mission-progress"><i style="width:${Math.min(100,value/mission.goal*100)}%"></i></div><small class="mission-progress-label">${claimed?'✓ 達成・受取済み':value>=mission.goal?'条件達成 · 幕クリアで受取':mission.trial?'条件を満たし、全6WAVEクリアで受取':`${value} / ${mission.goal}${mission.metric==='clears'?'回':mission.metric==='kills'?'体':'個'}`}</small></div></article>`;
}
export function currentMissions(profile,game){return `<section class="current-missions"><h3>${actLabel(game.act)} · ${game.actConfig.stages[game.area].name}</h3>${missionsFor(game.area,game.act).map(m=>missionRow(profile,m,game)).join('')}</section>`;}
export function missionsView(profile){return `<div class="rewards-intro"><span class="eyebrow">ACT MISSIONS</span><h2>冒険の足跡を、次の力に。</h2><p>各幕の全6WAVEを終え、最後の月の門へ。達成したミッションの報酬をまとめて受け取れます。ユニーク装備と追加の限界突破石は高難度の試練から。</p><span class="mission-total">${profile.missions.claimed.length} / ${STAGE_MISSIONS.length} 達成</span><button class="mission-challenge-button" data-prepare-challenge>チャレンジモードで準備する →</button></div>${ACTS.map(act=>`<section class="mission-act"><h3>${actLabel(act.id)} · ${act.title}<small>${missionsForAct(act.id).filter(m=>profile.missions.claimed.includes(m.id)).length} / ${missionsForAct(act.id).length} 達成</small></h3><div class="mission-stage-list">${act.stages.map((area,i)=>`<section class="mission-stage"><header style="--reward-scene:url('${area.image}')"><small>${area.waves}</small><h3>${area.name}</h3></header>${missionsFor(i,act.id).map(m=>missionRow(profile,m)).join('')}</section>`).join('')}</div></section>`).join('')}<p class="reward-note">各ミッション報酬は一度だけ自動受取。討伐・回収は出撃をまたいで累積します。途中で帰還した場合、ミッション報酬は次の幕クリアまで保留です。高難度の条件は一度の出撃中に達成し、そのまま幕をクリアしてください。会話・一時停止・祝福選択中には時間は進みません。各章の第4幕クリア報酬は限界突破石1個です。</p>`;}
export function equipmentView(profile,heroId,category='weapons'){
  const hero=HEROES.find(h=>h.id===heroId&&isHeroUnlocked(profile,h.id))??HEROES[0],signature=equippedWeapon(profile,hero.id),stats=combatStats(profile,hero),equipped=uniqueEquipment(profile.equipment.loadout[hero.id]);
  const owned=UNIQUE_EQUIPMENT.filter(item=>profile.equipment.owned.includes(item.id)),weaponCount=WEAPON_CATALOG.filter(item=>item.heroId===hero.id&&profile.weapons.owned.includes(item.id)).length;
  const unique=category==='unique';
  return `<div class="equipment-heading"><h2>装備</h2><p>入手した装備を、種類ごとに1個ずつ保管。</p></div><div class="equipment-character-picker" role="group" aria-label="装備するキャラクター">${HEROES.map(h=>`<button data-equipment-hero="${h.id}" ${isHeroUnlocked(profile,h.id)?'':'disabled'} title="${isHeroUnlocked(profile,h.id)?h.name:recruitmentNote(h.id)}" aria-pressed="${h.id===hero.id}"><span class="portrait ${h.id}"></span><span>${h.name}${!isHeroUnlocked(profile,h.id)?'<small>未加入</small>':''}</span></button>`).join('')}</div>
  <section class="equipment-current" aria-label="${hero.name}の現在の装備"><div class="equipment-slots"><article class="equipment-slot" data-current-weapon><img src="${weaponImage(signature)}" alt="" width="48" height="48" decoding="async"><div><small>専用武器 ${weaponRarityBadge(signature.rarity)}</small><strong>${signature.weapon.name}</strong><span>${weaponBonusText(signature)}</span></div></article><article class="equipment-slot" data-current-unique>${equipped?`<img src="${equipmentImage(equipped.id)}" alt="" width="48" height="48" decoding="async">`:`<span class="equipment-slot-empty">${icon('star')}</span>`}<div><small>ユニーク装備 · 共通1枠</small><strong>${equipped?.name??'未装備'}</strong><span>${equipped?equipmentBonusText(equipmentBonuses(profile.equipment,hero.id)):'所持品から選んで装備できます'}</span></div></article></div><dl class="equipment-statline" aria-label="装備込みの能力"><div><dt>HP</dt><dd>${stats.maxHp}</dd></div><div><dt>攻撃力</dt><dd>${Number(stats.attack.toFixed(1))}</dd></div><div><dt>防御力</dt><dd>${stats.defense}</dd></div></dl></section>
  <div class="equipment-category-picker" role="group" aria-label="装備の種類"><button data-equipment-category="weapons" aria-pressed="${!unique}">専用武器 <b>${weaponCount}</b></button><button data-equipment-category="unique" aria-pressed="${unique}">ユニーク装備 <b>${owned.length}</b></button></div>
  <div id="equipment-list-content">${!unique?`${weaponLoadoutView(profile,hero)}<button class="equipment-source-link" data-open-weapons>武器ガチャへ · 券 ${profile.inventory.weaponTicket}枚 ${icon('arrow')}</button>`:`<section class="equipment-inventory" aria-label="所持ユニーク装備"><p class="equipment-list-note">全キャラ共通・各1個。使用中の装備は、仲間から付け替えられます。</p>${owned.length?`<div class="equipment-list">${owned.map(item=>{
    const owner=equipmentOwner(profile.equipment,item.id),selected=owner===hero.id,other=owner&&!selected,ownerName=HEROES.find(h=>h.id===owner)?.name??'他の仲間';
    return `<article class="equipment-item ${selected?'equipped':''}" data-equipment-card="${item.id}" style="--item-color:${item.color}"><div class="equipment-item-main"><img class="equipment-thumbnail" src="${equipmentImage(item.id)}" alt="" width="56" height="56" loading="lazy" decoding="async"><div class="equipment-item-label"><small class="equipment-owner">${selected?'✓ 装備中':other?`${ownerName}が装備中`:'所持'}</small><h4>${item.name}</h4><p>${equipmentBonusText(item.bonus)}</p></div><button class="equipment-equip" data-equip-item="${item.id}" data-equip-hero="${hero.id}" aria-label="${item.name}を${selected?'外す':other?`${ownerName}から付け替える`:'装備する'}">${selected?'外す':other?'付け替え':'装備する'}</button></div></article>`;
  }).join('')}</div>`:`<div class="equipment-empty"><span>${icon('star')}</span><p>ユニーク装備はまだありません</p><small>各幕のチャレンジミッションで入手できます。</small><button class="equipment-source-link" data-menu-tab="missions">ミッションを見る ${icon('arrow')}</button></div>`}</section>`}</div>`;
}
