import {heroAbilities} from './abilities-ui.js';
import {isHeroUnlocked,recruitmentNote} from './recruitment.js';
import {HEROES,AREAS} from './model.js';
import {ACTS,actLabel} from './acts.js';
import {STAGE_MISSIONS,missionsFor,missionsForAct,missionIndex,trialStatus} from './missions.js';
import {WEAPONS,UNIQUE_EQUIPMENT,equipmentImage,uniqueEquipment,equipmentOwner,equipmentBonuses,equipmentBonusText} from './equipment.js';
import {resourceLabel} from './talents.js';
import {combatStats} from './progression.js';
import {icon} from './icons.js';

export function missionRewardText(mission){return [...Object.entries(mission.rewards).map(([id,n])=>`${resourceLabel(id)} ×${n}`),...(mission.equipment?[uniqueEquipment(mission.equipment).name]:[])].join(' ／ ');}
function missionRow(profile,mission,game){
  const claimed=profile.missions.claimed.includes(mission.id),value=profile.missions.stages[missionIndex(mission.act,mission.area)][mission.metric],trial=game&&mission.act===game.act&&mission.area===game.area?trialStatus(mission,game):null;
  return `<article class="mission-row ${claimed?'claimed':''} ${mission.trial?'challenge-mission':''}" data-mission="${mission.id}"><span class="mission-status">${icon(claimed?'check':mission.trial?'trophy':'compass')}</span><div><div class="mission-name"><h4>${mission.name}</h4>${mission.trial?'<span>高難度</span>':''}</div><p>${mission.description}</p>${!claimed&&trial?`<small class="trial-live ${trial.eligible?'eligible':'failed'}">${trial.hard?'チャレンジモード':'チャレンジモードが必要'} · ${trial.seconds.toFixed(1)} / ${mission.trial.seconds}秒 · 被弾 ${trial.hits} / ${mission.trial.hits}回${trial.eligible?' · 達成圏内':' · この挑戦は条件未達'}</small>`:''}<div class="mission-reward">${icon(mission.equipment?'star':mission.rewards.limitStone?'crystal':'spark')}${missionRewardText(mission)}</div><div class="mission-progress"><i style="width:${Math.min(100,value/mission.goal*100)}%"></i></div><small class="mission-progress-label">${claimed?'✓ 達成・受取済み':value>=mission.goal?'条件達成 · 幕クリアで受取':mission.trial?'条件を満たし、全6WAVEクリアで受取':`${value} / ${mission.goal}${mission.metric==='clears'?'回':mission.metric==='kills'?'体':'個'}`}</small></div></article>`;
}
export function currentMissions(profile,game){return `<section class="current-missions"><h3>${actLabel(game.act)} · ${game.actConfig.stages[game.area].name}</h3>${missionsFor(game.area,game.act).map(m=>missionRow(profile,m,game)).join('')}</section>`;}
export function missionsView(profile){return `<div class="rewards-intro"><span class="eyebrow">ACT MISSIONS</span><h2>冒険の足跡を、次の力に。</h2><p>各幕の全6WAVEを終え、最後の月の門へ。達成したミッションの報酬をまとめて受け取れます。ユニーク装備と追加の限界突破石は高難度の試練から。</p><span class="mission-total">${profile.missions.claimed.length} / ${STAGE_MISSIONS.length} 達成</span><button class="mission-challenge-button" data-prepare-challenge>チャレンジモードで準備する →</button></div>${ACTS.map(act=>`<section class="mission-act"><h3>${actLabel(act.id)} · ${act.title}<small>${missionsForAct(act.id).filter(m=>profile.missions.claimed.includes(m.id)).length} / ${missionsForAct(act.id).length} 達成</small></h3><div class="mission-stage-list">${act.stages.map((area,i)=>`<section class="mission-stage"><header style="--reward-scene:url('${area.image}')"><small>${area.waves}</small><h3>${area.name}</h3></header>${missionsFor(i,act.id).map(m=>missionRow(profile,m)).join('')}</section>`).join('')}</div></section>`).join('')}<p class="reward-note">各ミッション報酬は一度だけ自動受取。討伐・回収は出撃をまたいで累積します。途中で帰還した場合、ミッション報酬は次の幕クリアまで保留です。高難度の条件は一度の出撃中に達成し、そのまま幕をクリアしてください。会話・一時停止・祝福選択中には時間は進みません。各章の第4幕クリア報酬は限界突破石1個です。</p>`;}
export function equipmentView(profile,heroId){
  const hero=HEROES.find(h=>h.id===heroId&&isHeroUnlocked(profile,h.id))??HEROES[0],weapon=WEAPONS[hero.id],stats=combatStats(profile,hero),equipped=uniqueEquipment(profile.equipment.loadout[hero.id]);
  return `<div class="rewards-intro"><span class="eyebrow">SIGNATURE WEAPONS & RELICS</span><h2>この手に、冒険の証を。</h2><p>専用武器は最初から装備。ユニーク装備はキャラごとに1枠。好きな所持品を選んで付け替えられます。</p></div><div class="equipment-heroes" role="group" aria-label="装備するキャラクター">${HEROES.map(h=>`<button data-equipment-hero="${h.id}" ${isHeroUnlocked(profile,h.id)?'':'disabled'} title="${isHeroUnlocked(profile,h.id)?h.name:recruitmentNote(h.id)}" aria-pressed="${h.id===hero.id}"><span class="portrait ${h.id}"></span><span>${h.name}<small>${!isHeroUnlocked(profile,h.id)?recruitmentNote(h.id):h.role}</small></span></button>`).join('')}</div>${heroAbilities(hero,profile.characters[hero.id])}<section class="signature-weapon ${weapon.kind}"><div class="weapon-symbol"><img src="${equipmentImage(weapon.id)}" alt="${weapon.name}" width="256" height="256" decoding="async"></div><div><small>${hero.name}専用 / 装備中</small><h3>${weapon.name}</h3><p>${weapon.note}</p><span>基礎威力 ${hero.damage} · 射程 ${hero.range} · 攻撃間隔 ${hero.interval}秒</span></div></section><section class="equipped-summary"><span>ユニーク装備 <b>${equipped?.name??'未装備'}</b><small>${equipped?equipmentBonusText(equipmentBonuses(profile.equipment,hero.id)):'試練を達成して装備を集めよう'}</small></span><dl><div><dt>装備込みHP</dt><dd>${stats.maxHp}</dd></div><div><dt>攻撃力</dt><dd>${Number(stats.attack.toFixed(1))}</dd></div><div><dt>防御力</dt><dd>${stats.defense}</dd></div></dl></section><div class="unique-equipment-list">${UNIQUE_EQUIPMENT.map(item=>{
    const owned=profile.equipment.owned.includes(item.id),owner=equipmentOwner(profile.equipment,item.id),selected=owner===hero.id,other=owner&&!selected,mission=STAGE_MISSIONS.find(m=>m.equipment===item.id);
    return `<article class="unique-card ${owned?'owned':'locked'} ${selected?'equipped':''}" data-equipment-card="${item.id}" style="--relic-color:${item.color}"><div class="relic-symbol"><img src="${equipmentImage(item.id)}" alt="${item.name}" width="256" height="256" loading="lazy" decoding="async"></div><small>${actLabel(item.act??0)} / UNIQUE</small><h3>${item.name}</h3><p>${item.note}</p><div class="relic-source"><b>${ACTS[item.act??0].stages[item.area].name}「${mission.name}」</b><span>${mission.description}</span></div><button data-equip-item="${item.id}" data-equip-hero="${hero.id}" ${!owned?'disabled':''}>${selected?'装備を外す':other?`${HEROES.find(h=>h.id===owner)?.name??'他の仲間'}から付け替え`:owned?'装備する':'試練達成で入手'}</button>${!owned?`<button class="relic-mission-link" data-show-mission="${mission.id}">ミッションを見る →</button>`:''}</article>`;
  }).join('')}</div><p class="reward-note">ユニーク装備は各1個。同じ装備は一人が使用します。「付け替え」で、他の仲間から移すこともできます。装備変更はメニューで行い、次の冒険から有効です。</p>`;
}
