import {isHeroUnlocked,recruitmentNote} from './recruitment.js';
import {HEROES} from './model.js';
import {icon} from './icons.js';
import {ultimateFor} from './abilities.js';
import {characterProgress,characterStats,talentStatus,levelCap,previewLimitBreak} from './progression.js';
import {MATERIALS,TREE_RESOURCES,FIRST_TIER_NODES,SECOND_TIER_NODES,LIMIT_BREAK_NODES,GROWTH_NODES,talentNode,talentBonuses,ultimateBonuses,bonusText,nodeEffectText,growthCount,resourceLabel,tierMaterialCost} from './talents.js';

export function materialsText(amounts){return Object.entries(MATERIALS).filter(([id])=>(amounts[id]??0)>0).map(([id,m])=>`${resourceLabel(id)} +${amounts[id].toLocaleString()}`).join(' ／ ')||'素材はまだありません';}
export function materialWallet(profile){return `<div class="material-wallet" aria-label="共有の成長素材と限界突破石">${Object.entries(TREE_RESOURCES).map(([id,m])=>`<div class="material-item ${id} rarity-${m.rarity??'special'}" title="${m.note}">${icon(m.icon)}<div><span><em class="rarity-tag">${m.rarity?`★${m.rarity} · レア度${m.rarity}`:'専用 · 限界突破'}</em>${m.name}</span><strong data-material-count="${id}">${(profile.inventory[id]??0).toLocaleString()}</strong><small>${m.source}</small></div></div>`).join('')}</div>`;}
function tierCostText(nodes){return Object.entries(tierMaterialCost(nodes)).map(([id,n])=>`${resourceLabel(id)} ${n.toLocaleString()}個`).join(' ／ ');}

function limitDetail(profile,hero,node){
  const p=characterProgress(profile,hero.id),status=talentStatus(profile,hero.id,node.id),preview=previewLimitBreak(profile,hero.id,node.id),stone=TREE_RESOURCES.limitStone;
  const reasons=[status.parents.length?`先に「${status.parents.map(id=>talentNode(id,hero.id).name).join('」「')}」を解放`:'',!status.levelMet?`キャラLv.${node.level}が必要（現在Lv.${p.level}）`:'',status.missing.length?`限界突破石が${status.missing[0].needed-status.missing[0].owned}個不足`:''].filter(Boolean);
  return `<aside class="talent-detail limit-detail" id="talent-detail" aria-label="選択した限界突破"><div class="talent-detail-heading"><span class="talent-detail-icon">${icon('crystal')}</span><div><small>LEVEL LIMIT / ${status.owned?'UNLOCKED':`STEP ${node.stage}`}</small><h3>${node.name}</h3></div></div><p class="talent-effect">${nodeEffectText(node)}</p><p class="talent-permanent">${hero.name}のレベル上限を解放</p><div class="limit-cap-preview"><span><small>解放前の上限</small>Lv.<b>${node.level}</b></span>${icon('arrow')}<span><small>解放後の上限</small>Lv.<b>${node.cap}</b></span></div><dl class="talent-preview"><div><dt>現在のキャラレベル</dt><dd id="limit-current-level">Lv.${p.level} <span>/ ${levelCap(p)}</span></dd></div><div><dt>${p.level>=levelCap(p)?'蓄積経験値':'経験値'}</dt><dd>${p.xp.toLocaleString()}</dd></div>${preview?`<div><dt>解放後のレベル</dt><dd id="limit-next-level">Lv.${p.level}<span> → <b>${preview.level}</b></span></dd></div>`:''}</dl>${status.owned?`<p class="talent-owned-note">✓ 上限Lv.${node.cap}は解放済みです。<br>現在の上限はLv.${levelCap(p)}です。</p>`:`<h4>必要なアイテム <small>所持 / 必要</small></h4><ul class="talent-cost"><li class="${status.missing.length?'shortage':''}">${icon(stone.icon)}<span>${stone.name}</span><b>${profile.inventory.limitStone} <small>/ ${node.cost.limitStone}</small></b></li></ul><p class="limit-source">各章の第4幕をクリアするたびに1個獲得</p><div class="talent-requirements">${reasons.length?reasons.map(text=>`<p>${text}</p>`).join(''):'<p class="ready">限界突破できます</p>'}</div>`}<button class="talent-unlock" data-unlock-node="${node.id}" data-unlock-hero="${hero.id}" ${status.canUnlock?'':'disabled'}>${status.owned?'解放済み':status.canUnlock?`限界突破する · 石${node.cost.limitStone}個`:status.parents.length?'前の限界突破が必要です':!status.levelMet?`Lv.${node.level}で限界突破`:'限界突破石が足りません'}</button><p class="talent-spend-note">上限に達した後の経験値は蓄積し、限界突破で反映します。限界突破石は仲間で共有します。</p></aside>`;
}
function treeNodeButton(profile,hero,node,selected){
  const status=talentStatus(profile,hero.id,node.id),state=status.owned?'解放済み':status.canUnlock?'解放可能':'未解放',limit=node.kind==='limit';
  return `<button class="talent-node ${limit?'limit-node ':''}${status.owned?'unlocked':status.canUnlock?'available':'locked'} ${selected.id===node.id?'selected':''}" data-tree-node="${node.id}" style="--node-x:${node.x}%;--node-y:${node.y}%" aria-pressed="${selected.id===node.id}" aria-label="${node.name}${limit?`、上限Lv.${node.cap}`:''}：${state}"><span class="talent-orb">${limit?`<b class="limit-cap-number">${node.cap}</b>`:icon(node.icon)}<i>${status.owned?'✓':status.canUnlock?'+':node.level}</i></span><strong>${node.name}</strong><small>${limit?`上限Lv.${node.cap} · `:''}${state}</small></button>`;
}
function limitBranch(profile,hero,selected){
  const p=characterProgress(profile,hero.id);
  const edges=LIMIT_BREAK_NODES.slice(1).map(node=>{const previous=talentNode(node.parents[0],hero.id),status=talentStatus(profile,hero.id,node.id);return `<path class="${status.owned?'lit':!status.parents.length?'reachable':''}" d="M ${previous.x} 40 H ${node.x}"/>`;}).join('');
  return `<section class="limit-branch" aria-label="レベル限界突破の道"><header><div><small>LEVEL LIMIT</small><h4>レベルの道</h4></div><span>現在の上限 <b>Lv.${levelCap(p)}</b></span></header><p>上限Lv.20から始まる道。各段階に限界突破石1個。</p><div class="limit-map"><svg class="talent-links" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${edges}</svg>${LIMIT_BREAK_NODES.map(node=>treeNodeButton(profile,hero,node,selected)).join('')}</div></section>`;
}
function ultimatePreview(hero,character,node,owned){
  const spec=ultimateFor(hero.id,character),percent=n=>`${Math.round(n*100)}%`,number=n=>Number(n.toFixed(2));
  const fields={ultimateDamage:['必殺技威力補正','power',percent],ultimateCharge:['ゲージ獲得補正','chargeMultiplier',percent],ultimateHeal:['HP回復量','heal',number],ultimateRadius:['攻撃半径','radius',number],ultimatePierce:['貫通する敵の数','pierce',n=>`${n}体`],ultimateRange:['必殺弾の射程','range',number],ultimateImmunity:['無敵時間','immunity',n=>`${number(n)}秒`],ultimatePulses:['攻撃回数','pulses',n=>`${n}回`],ultimateShots:['連射数','shots',n=>`${n}発`]};
  const rows=Object.entries(node.bonus).filter(([key])=>fields[key]).map(([key,value])=>{const [label,field,format]=fields[key],current=spec[field];return `<div><dt>${label}</dt><dd>${format(current)}${owned?'':` <span>→ <b>${format(current+value)}</b></span>`}</dd></div>`;}).join('');
  return rows?`<p class="ultimate-preview-name">${spec.name}</p><dl class="talent-preview ultimate-preview">${rows}</dl>`:'';
}
function detail(profile,hero,node){
  if(node.kind==='limit')return limitDetail(profile,hero,node);
  const character=characterProgress(profile,hero.id),status=talentStatus(profile,hero.id,node.id),stats=characterStats(hero,character);
  const tree=talentBonuses(character,hero.id),next=status.owned?stats:{maxHp:stats.maxHp+(node.bonus.hp??0),defense:stats.defense+(node.bonus.defense??0),attack:stats.attack/(1+tree.attack)*(1+tree.attack+(node.bonus.attack??0))};
  const reasons=[!status.levelMet?`キャラLv.${node.level}が必要（現在Lv.${character.level}）`:'',status.parents.length?`先に「${status.parents.map(id=>talentNode(id,hero.id).name).join('」「')}」を解放`:'',status.missing.length?`${status.missing.map(m=>`${resourceLabel(m.id)}が${m.needed-m.owned}個不足`).join('、')}`:''].filter(Boolean);
  return `<aside class="talent-detail" id="talent-detail" aria-label="選択した成長ノード"><div class="talent-detail-heading"><span class="talent-detail-icon">${icon(node.icon)}</span><div><small>${node.branch} / ${status.owned?'UNLOCKED':`Lv.${node.level}〜`}</small><h3>${node.name}</h3></div></div><p class="talent-effect">${bonusText(node.bonus)}</p><p class="talent-permanent">${hero.name}にずっと有効</p>${ultimatePreview(hero,character,node,status.owned)}<dl class="talent-preview">${[['基礎HP','maxHp'],['基礎攻撃力','attack'],['基礎防御力','defense']].map(([label,id])=>`<div><dt>${label}</dt><dd>${Number(stats[id].toFixed(1))}${!status.owned&&stats[id]!==next[id]?` <span>→ <b>${Number(next[id].toFixed(1))}</b></span>`:''}</dd></div>`).join('')}</dl>${status.owned?'<p class="talent-owned-note">✓ この星は解放済みです。<br>効果は基礎能力・必殺技に反映されています。</p>':`<h4>解放に必要な素材</h4><ul class="talent-cost">${Object.entries(node.cost).map(([id,cost])=>`<li class="${profile.inventory[id]<cost?'shortage':''}">${icon(MATERIALS[id].icon)}<span>${resourceLabel(id)}<small class="cost-source">${MATERIALS[id].source}</small></span><b>${profile.inventory[id]} <small>/ ${cost}</small></b></li>`).join('')}</ul><div class="talent-requirements">${reasons.length?reasons.map(text=>`<p>${text}</p>`).join(''):'<p class="ready">解放条件を満たしています</p>'}</div>`}<button class="talent-unlock" data-unlock-node="${node.id}" data-unlock-hero="${hero.id}" ${status.canUnlock?'':'disabled'}>${status.owned?'解放済み':status.canUnlock?'素材を使って解放':!status.levelMet?`Lv.${node.level}で解放可能`:status.parents.length?'前の星を解放してください':'素材が足りません'}</button><p class="talent-spend-note">素材は仲間で共有。解放はキャラごとに行います。</p></aside>`;
}
export function talentView(profile,heroId,selectedId='origin'){
  const hero=HEROES.find(h=>h.id===heroId&&isHeroUnlocked(profile,h.id))??HEROES[0],character=characterProgress(profile,hero.id),tree=character.tree??[],selected=talentNode(selectedId,hero.id)??talentNode('origin',hero.id),bonus={...talentBonuses(character,hero.id),...ultimateBonuses(character,hero.id)},tier=selected.tier??1,nodes=tier===2?SECOND_TIER_NODES:FIRST_TIER_NODES;
  const edges=nodes.flatMap(node=>node.parents.filter(id=>nodes.some(n=>n.id===id)).map(id=>{const parent=talentNode(id,hero.id),active=tree.includes(node.id),ready=tree.includes(id);return `<path class="${active?'lit':ready?'reachable':''}" d="M ${parent.x} ${parent.y} C ${parent.x} ${(parent.y+node.y)/2}, ${node.x} ${(parent.y+node.y)/2}, ${node.x} ${node.y}"/>`;})).join('');
  return `${materialWallet(profile)}<div class="tree-hero-picker" role="group" aria-label="成長させるキャラ">${HEROES.map(h=>`<button data-tree-hero="${h.id}" ${isHeroUnlocked(profile,h.id)?'':'disabled'} title="${isHeroUnlocked(profile,h.id)?h.name:recruitmentNote(h.id)}" aria-pressed="${hero.id===h.id}"><span class="portrait ${h.id}" role="img" aria-label="${h.name}"></span><span><strong>${h.name}</strong><small>${isHeroUnlocked(profile,h.id)?`Lv.${characterProgress(profile,h.id).level} · ${growthCount(characterProgress(profile,h.id))} / ${GROWTH_NODES.length} 解放`:recruitmentNote(h.id)}</small></span></button>`).join('')}</div><div class="tree-workbench ${hero.id}"><div class="talent-map-wrap"><div class="talent-map-heading"><div><small>${hero.id==='nyanluna'?'LUNAR CONSTELLATION':hero.id==='omsolo'?'EMERALD CONSTELLATION':'STELLAR CONSTELLATION'}</small><h3>${hero.name}の成長ツリー</h3></div><span>${growthCount(character)}<small> / ${GROWTH_NODES.length}</small></span></div>${limitBranch(profile,hero,selected)}<nav class="tree-tiers" aria-label="成長ツリーの段を選ぶ">${[[1,FIRST_TIER_NODES,'基礎の星'],[2,SECOND_TIER_NODES,'覚醒と必殺技']].map(([n,list,title])=>`<button data-tree-tier="${n}" aria-pressed="${tier===n}"><small>${n===1?'Lv.1–15':'Lv.30–50'}</small><strong>${n}段目 · ${title}</strong><span>${list.filter(node=>tree.includes(node.id)).length} / ${list.length} 解放</span></button>`).join('')}</nav>${tier===2?`<section class="tier-gate ${tree.includes('awakening')&&character.level>=30?'ready':''}"><strong>2段目 · 覚醒への挑戦</strong><p>1段目の全8星とLv.30が入口。レア度1の星の芽に加え、レア度2の月虹のしずく・深星の核が必要です。最後の超覚醒はLv.50で解放。</p><div><span>${tree.includes('awakening')?'✓':'○'} 1段目を全解放</span><span>${character.level>=30?'✓':'○'} Lv.30以上</span></div><small>2段目すべての素材：${tierCostText(SECOND_TIER_NODES)}</small></section>`:`<section class="tier-gate tier-one-guide"><strong>1段目 · レア度1だけで強化</strong><p>星の芽・月のしずく・守護者の核で全8星を解放できます。レア度2の素材は使いません。</p><small>1段目すべての素材：${tierCostText(FIRST_TIER_NODES)}</small></section>`}<div class="talent-path-label"><span>${tier===2?'AWAKENED STARS':'ABILITY STARS'}</span><strong>${tier}段目 · ${tier===2?'覚醒の星':'能力の星'}</strong></div><div class="talent-map" role="group" aria-label="星を選ぶと効果と解放条件を表示"><svg class="talent-links" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${edges}</svg>${nodes.map(base=>treeNodeButton(profile,hero,talentNode(base.id,hero.id),selected)).join('')}</div><div class="talent-legend"><span>● 解放済み</span><span>◌ 解放可能</span><span>数字は必要Lv.</span></div><div class="tree-total"><small>ツリーによる成長</small><strong>${bonusText(bonus)||'星を選んで、最初の力を解放しよう。'}</strong></div></div>${detail(profile,hero,selected)}</div><div class="material-guide"><h3>素材の集め方</h3>${Object.entries(TREE_RESOURCES).map(([id,m])=>`<p>${icon(m.icon)}<strong>${resourceLabel(id)}</strong><span>${m.note}</span></p>`).join('')}<small>獲得した素材と解放した星は自動保存。途中で冒険を終えても残ります。</small></div>`;
}
