import {HEROES} from './model.js';
import {combatStats} from './progression.js';
import {isHeroUnlocked,recruitmentNote} from './recruitment.js';
import {WEAPON_CATALOG,WEAPON_HERO_IDS,WEAPON_RARITIES,WEAPON_TICKET_DROP_RATE,WEAPON_MULTI_DRAW_COUNT,equippedWeapon,weaponVariant,weaponImage,weaponAttackProfile,rarityLabel} from './weapons.js';
import {icon} from './icons.js';

const fmt=n=>Number(n.toFixed(2));
export const weaponBonusText=item=>`${item.weapon.style} · 攻撃力 +${Math.round(item.bonus.attack*100)}%${item.bonus.defense?` · 防御力 +${item.bonus.defense}`:''}`;
export const weaponRarityBadge=rarity=>`<span class="weapon-rarity" data-rank="${rarity.rank}" style="--rarity-color:${rarity.color}">${rarityLabel(rarity)}</span>`;
const heroName=id=>HEROES.find(h=>h.id===id).name;
export function weaponLoadoutView(profile,hero){
 const equipped=equippedWeapon(profile,hero.id),current={...combatStats(profile,hero),...weaponAttackProfile(profile,hero)};
 const fields=[['攻撃力','attack',false,''],['防御力','defense',false,''],['攻撃間隔','interval',true,'秒'],['射程','range',false,''],...(hero.id==='tsukineko'?[['貫通数','pierce',false,'体']]:hero.id==='mochinyafe'?[['援護間隔','supportInterval',true,'秒'],['援護射程','supportRange',false,''],['援護貫通','supportPierce',false,'体']]:[])];
 const owned=WEAPON_CATALOG.filter(item=>item.heroId===hero.id&&profile.weapons.owned.includes(item.id)).sort((a,b)=>b.rarity.rank-a.rarity.rank);
 return `<section class="equipment-inventory" aria-label="${hero.name}の所持専用武器"><p class="equipment-list-note">${hero.id==='mochinyafe'?'3系統の鈴で通常音弾と援護を調整。攻撃力は低くても、音弾の命中時は最低1ダメージ。':'同じ武器でもレア度ごとに1本ずつ保管。付け替えても手元に残ります。'}</p><div class="equipment-list">${owned.map(item=>{
 const selected=item.id===equipped.id,preview={...profile,weapons:{...profile.weapons,loadout:{...profile.weapons.loadout,[hero.id]:item.id}}},stats={...combatStats(preview,hero),...weaponAttackProfile(preview,hero)};
 return `<article class="equipment-item ${selected?'equipped':''}" data-weapon-option="${item.id}" style="--item-color:${item.rarity.color}"><div class="equipment-item-main"><img class="equipment-thumbnail" src="${weaponImage(item)}" alt="" width="56" height="56" loading="lazy" decoding="async"><div class="equipment-item-label">${weaponRarityBadge(item.rarity)}<h4>${item.weapon.name}</h4><p>${item.weapon.style} · 攻撃力 ${fmt(stats.attack)}${item.bonus.defense?` · 防御 +${item.bonus.defense}`:''}</p></div><button class="equipment-equip" data-equip-weapon="${item.id}" data-weapon-hero="${hero.id}" aria-label="${item.weapon.name} ★${item.rarity.rank}${selected?' 装備中':'を装備する'}" ${selected?'disabled':''}>${selected?'✓ 装備中':'装備する'}</button></div><details class="equipment-item-details" data-equipment-detail="${item.id}"><summary>性能を比較</summary><p>${item.weapon.note}</p><dl class="weapon-comparison">${fields.map(([label,key,inverse,unit])=>{const diff=fmt(stats[key]-current[key]),better=inverse?diff<0:diff>0;return `<div><dt>${label}</dt><dd>${fmt(stats[key])}${unit}<small class="${diff?(better?'better':'worse'):'same'}" aria-label="装備中との差 ${diff>0?'+':''}${diff}${unit}">${diff?`${diff>0?'+':''}${diff}`:'—'}</small></dd></div>`;}).join('')}</dl><p class="equipment-comparison-note">育成・ユニーク装備込み。差分は装備中との比較です。攻撃間隔は短いほど速く、間隔・射程・貫通数は通常攻撃に適用されます。${hero.id==='mochinyafe'?'援護の項目は、控えで放つ「ふぇ〜」に適用されます。':''}</p></details></article>`;
 }).join('')}</div></section>`;
}
export function weaponGachaView(profile){
 const tickets=profile.inventory.weaponTicket,last=weaponVariant(profile.weapons.lastDraw?.weaponId),batch=profile.weapons.lastBatch;
 return `<div class="rewards-intro"><span class="eyebrow">SIGNATURE WEAPON SUMMON</span><h2>星の向こうから、届く一本。</h2><p>にゃんるなの杖、つきねこの銃、オムソロの光剣、もちにゃふぇの鈴。<br>★2〜★4は各キャラ・各レア度に3種類。36本の中から、どの一本に出会えるだろう。</p></div>
 <section class="weapon-summon" aria-label="専用武器ガチャ"><div class="summon-emblem">${icon('star')}</div><span class="eyebrow">FOUR FRIENDS · ONE TICKET</span><h3>専用武器ガチャ</h3><p>★2以上の武器が、いずれかのキャラに1本。</p><div class="weapon-ticket-wallet">${icon('spark')}<span>専用武器ガチャ券<strong id="weapon-ticket-count">${tickets.toLocaleString()}<small>枚</small></strong></span></div><div class="weapon-draw-options"><button class="primary" data-draw-weapon ${tickets<1?'disabled':''}>${icon('star')}<span>${tickets>0?'ガチャを1回まわす':'ガチャ券がありません'}<small>専用武器ガチャ券 ×1 を使用</small></span>${icon('arrow')}</button><button class="primary multi-draw" data-draw-weapons ${tickets<WEAPON_MULTI_DRAW_COUNT?'disabled':''}>${icon('star')}<span>ガチャを10連でまわす<small>専用武器ガチャ券 ×10 を使用</small></span>${icon('arrow')}</button></div><p class="ticket-source">各幕の全6WAVEクリアで、毎回必ず1枚。クリア済みの幕でも入手できます。<br>通常ボス・強ボスからは、さらに${WEAPON_TICKET_DROP_RATE*100}%で1枚。<br>第3章の金色のスライムは、討伐1体ごとに10枚確定。<br>ドロップした券はすぐに保存され、途中帰還・敗北でも持ち帰れます。</p></section>
 ${batch?`<section class="last-weapon-batch"><h3>前回の10連結果</h3>${weaponBatchCards(batch.map(draw=>({item:weaponVariant(draw.weaponId),duplicate:draw.duplicate,duplicateBuds:draw.duplicateBuds??0})),profile,false)}</section>`:last?`<section class="last-weapon-draw"><small>前回の結果 · ${profile.weapons.draws}回目</small><strong>${heroName(last.heroId)}専用 · ${last.weapon.name}</strong>${weaponRarityBadge(last.rarity)}<span>${profile.weapons.lastDraw.duplicate?`重複 → 星の芽 ×${profile.weapons.lastDraw.duplicateBuds}`:'新しい武器を獲得'}</span></section>`:''}
 <details class="weapon-odds"><summary>提供割合・重複時の内容を見る</summary><p>キャラは4人から均等に抽選（各25%）。レア度を決め、その中の武器3種類から均等に抽選します。編成・加入状況・所持武器によって確率は変わりません。10連は同じ割合で10回抽選します。</p><table><thead><tr><th>レア度</th><th>合計</th><th>各武器1本</th><th>重複時</th></tr></thead><tbody>${WEAPON_RARITIES.filter(r=>r.chance).map(r=>`<tr><th>${rarityLabel(r)}</th><td>${r.chance*100}%</td><td>約${(r.chance*100/(WEAPON_HERO_IDS.length*3)).toFixed(4)}%</td><td>星の芽 ×${r.duplicateBuds}</td></tr>`).join('')}</tbody></table><p>各武器の確率は小数点以下を丸めています。★1は初期装備のため抽選に含まれません。所持済みの「同じ武器・同じレア度」だけを星の芽へ変換。別の武器なら同じキャラ・レア度でも新規獲得です。未加入キャラの武器も保管され、加入後に使用できます。</p></details>
 <div class="weapon-collection-heading"><h3>専用武器コレクション</h3><p>各キャラ10本。獲得した武器は「装備」で自由に付け替え。<br>ガチャでは装備を変更しません。ユニーク装備は別の1枠です。</p></div><div class="weapon-collection">${HEROES.filter(hero=>WEAPON_HERO_IDS.includes(hero.id)).map(hero=>{const item=equippedWeapon(profile,hero.id),unlocked=isHeroUnlocked(profile,hero.id),count=WEAPON_CATALOG.filter(w=>w.heroId===hero.id&&profile.weapons.owned.includes(w.id)).length;return `<article class="weapon-collection-card" data-weapon-hero="${hero.id}" style="--rarity-color:${item.rarity.color}"><header><span class="portrait ${hero.id}"></span><div><h4>${hero.name}</h4><small>${unlocked?'現在の装備':'加入まで保管'} · ${count} / 10本所持</small></div></header><img src="${weaponImage(item)}" alt="${item.weapon.name}" width="256" height="256" decoding="async">${weaponRarityBadge(item.rarity)}<h4>${item.weapon.name}</h4><p>${weaponBonusText(item)}</p>${!unlocked?`<p class="weapon-unlock-note">${recruitmentNote(hero.id)}</p>`:`<button class="secondary" data-open-equipment="${hero.id}">武器を選んで付け替える →</button>`}</article>`;}).join('')}</div>`;
}
export function weaponDrawResult(result,profile,storageAvailable){
 const {item,duplicate,duplicateBuds}=result,unlocked=isHeroUnlocked(profile,item.heroId),selected=equippedWeapon(profile,item.heroId).id===item.id;
 // The summon stage shows the weapon art; this is the title and sheet revealed over it.
 return `<section id="weapon-draw-result" class="weapon-draw-result" data-rank="${item.rarity.rank}" style="--rarity-color:${item.rarity.color}"><header class="draw-title"><p class="draw-stars" aria-hidden="true">${Array.from({length:item.rarity.rank},()=>'<i>★</i>').join('')}</p><div class="draw-name"><span class="eyebrow draw-badge${duplicate?' is-duplicate':''}">${duplicate?'DUPLICATE REWARD':'NEW WEAPON'}</span><h2 id="weapon-draw-name">${item.weapon.name}</h2><p class="draw-hero"><span class="portrait ${item.heroId}"></span>${heroName(item.heroId)}専用 ${weaponRarityBadge(item.rarity)}</p></div></header><div class="draw-sheet"><p class="draw-headline">${duplicate?'武器の力を、育成へ。':'新しい専用武器を獲得！'}</p><p class="draw-bonus">${weaponBonusText(item)}<span class="draw-note">${item.weapon.note}</span></p><div class="draw-outcome">${duplicate?`所持済みのため 星の芽 <b>+${duplicateBuds}</b>`:!unlocked?'加入後に使えるよう保管しました':'コレクションに追加しました。装備は変更していません。'}</div><p class="draw-saved">残り ${profile.inventory.weaponTicket}枚 · ${storageAvailable?'結果を保存しました':'この環境では保存できません'}</p><div class="draw-actions">${unlocked?`<button class="secondary draw-equip" data-equip-weapon="${item.id}" data-weapon-hero="${item.heroId}" ${selected?'disabled':''}>${selected?'✓ この武器を装備中':'この武器を装備する'}</button>`:''}<button class="primary" data-close>結果を閉じる ${icon('check')}</button></div></div></section>`;
}

function weaponBatchCards(results,profile,allowEquip){
 return `<ol class="weapon-batch-grid">${results.map(({item,duplicate,duplicateBuds},index)=>{const unlocked=isHeroUnlocked(profile,item.heroId),selected=equippedWeapon(profile,item.heroId).id===item.id;return `<li class="weapon-batch-card" data-batch-item="${item.id}" data-rank="${item.rarity.rank}" style="--rarity-color:${item.rarity.color};--batch-index:${index}"><span class="batch-card-top"><small>${String(index+1).padStart(2,'0')}</small><b class="${duplicate?'is-duplicate':''}">${duplicate?'重複':'NEW'}</b></span><img src="${weaponImage(item)}" alt="" width="88" height="88" decoding="async">${weaponRarityBadge(item.rarity)}<h3>${item.weapon.name}</h3><p>${heroName(item.heroId)}専用</p><span class="batch-outcome">${duplicate?`星の芽 +${duplicateBuds}`:unlocked?'新規獲得':'加入まで保管'}</span>${allowEquip&&unlocked?`<button class="secondary" data-equip-weapon="${item.id}" data-weapon-hero="${item.heroId}" aria-label="${item.weapon.name} ★${item.rarity.rank}を装備する" ${selected?'disabled':''}>${selected?'装備中':'装備する'}</button>`:''}</li>`;}).join('')}</ol>`;
}
export function weaponBatchResult(results,profile,storageAvailable){
 const added=results.filter(r=>!r.duplicate).length,buds=results.reduce((sum,r)=>sum+r.duplicateBuds,0);
 const counts=[4,3,2].map(rank=>({rank,count:results.filter(r=>r.item.rarity.rank===rank).length})).filter(r=>r.count);
 return `<section id="weapon-draw-result" class="weapon-batch-result" aria-labelledby="weapon-draw-name"><header class="batch-result-header"><span class="eyebrow">TENFOLD LUNAR SUMMON · COMPLETE</span><h2 id="weapon-draw-name">10連ガチャの結果</h2><div class="batch-rarity-totals" aria-label="レア度別の獲得数">${counts.map(({rank,count})=>`<span data-rank="${rank}">★${rank} <b>×${count}</b></span>`).join('')}</div><p>新規 ${added}本 ／ 重複 ${results.length-added}本${buds?` · 星の芽 +${buds}`:''}</p></header>${weaponBatchCards(results,profile,true)}<footer class="batch-result-footer"><p>残り ${profile.inventory.weaponTicket}枚 · ${storageAvailable?'10回分の結果を保存しました':'この環境では保存できません'}</p><button class="primary" data-close>結果を閉じる ${icon('check')}</button></footer></section>`;
}
