import {HEROES} from './model.js';
import {combatStats} from './progression.js';
import {isHeroUnlocked,recruitmentNote} from './recruitment.js';
import {WEAPON_CATALOG,WEAPON_RARITIES,WEAPON_TICKET_DROP_RATE,equippedWeapon,weaponVariant,weaponImage,weaponAttackProfile,rarityLabel} from './weapons.js';
import {icon} from './icons.js';

const fmt=n=>Number(n.toFixed(2));
export const weaponBonusText=item=>`${item.weapon.style} · 攻撃力 +${Math.round(item.bonus.attack*100)}%${item.bonus.defense?` · 防御力 +${item.bonus.defense}`:''}`;
export const weaponRarityBadge=rarity=>`<span class="weapon-rarity" style="--rarity-color:${rarity.color}">${rarityLabel(rarity)}</span>`;
const heroName=id=>HEROES.find(h=>h.id===id).name;
export function weaponLoadoutView(profile,hero){
 const equipped=equippedWeapon(profile,hero.id),current={...combatStats(profile,hero),...weaponAttackProfile(profile,hero)};
 const fields=[['攻撃力','attack',false,''],['防御力','defense',false,''],['攻撃間隔','interval',true,'秒'],['射程','range',false,''],...(hero.id==='tsukineko'?[['貫通数','pierce',false,'体']]:[])];
 return `<section class="weapon-loadouts" aria-label="${hero.name}の専用武器"><header><span class="eyebrow">CHOOSE YOUR STYLE</span><h3>この冒険に、どの一本を。</h3><p>同じレア度にも3種類の個性。所持武器は何度でも自由に付け替えられます。<br>数値は育成・ユニーク装備込み。差分は装備中との比較です。攻撃間隔は短いほど速くなります。<br>攻撃間隔・射程・貫通数は通常攻撃に適用。攻撃力は攻撃スキルにも反映されます。</p></header>${WEAPON_RARITIES.map(r=>`<section class="weapon-loadout-rank"><h4>${weaponRarityBadge(r)}<small>${r.rank===1?'いつでも戻せる初期装備':'3種類から、戦い方で選ぼう'}</small></h4><div class="weapon-loadout-grid">${WEAPON_CATALOG.filter(item=>item.heroId===hero.id&&item.rarity===r).map(item=>{
 const owned=profile.weapons.owned.includes(item.id),selected=item.id===equipped.id,preview={...profile,weapons:{...profile.weapons,owned:[...profile.weapons.owned,item.id],loadout:{...profile.weapons.loadout,[hero.id]:item.id}}},stats={...combatStats(preview,hero),...weaponAttackProfile(preview,hero)};
 return `<article class="weapon-option ${owned?'owned':'locked'} ${selected?'equipped':''}" data-weapon-option="${item.id}" style="--rarity-color:${r.color}"><div class="weapon-option-art"><img src="${weaponImage(item)}" alt="${item.weapon.name}" width="256" height="256" loading="lazy" decoding="async"><span>${selected?'装備中':owned?'所持':'未所持'}</span></div><small>${item.weapon.style}</small><h4>${item.weapon.name}</h4><p>${item.weapon.note}</p><dl class="weapon-comparison">${fields.map(([label,key,inverse,unit])=>{const diff=fmt(stats[key]-current[key]),better=inverse?diff<0:diff>0;return `<div><dt>${label}</dt><dd>${fmt(stats[key])}${unit}<small class="${diff?(better?'better':'worse'):'same'}" aria-label="装備中との差 ${diff>0?'+':''}${diff}${unit}">${diff?`${diff>0?'+':''}${diff}`:'—'}</small></dd></div>`;}).join('')}</dl><button data-equip-weapon="${item.id}" data-weapon-hero="${hero.id}" aria-pressed="${selected}" ${!owned||selected?'disabled':''}>${selected?'✓ 装備中':owned?'この武器を装備':'ガチャで入手'}</button></article>`;
 }).join('')}</div></section>`).join('')}</section>`;
}
export function weaponGachaView(profile){
 const tickets=profile.inventory.weaponTicket,last=weaponVariant(profile.weapons.lastDraw?.weaponId);
 return `<div class="rewards-intro"><span class="eyebrow">SIGNATURE WEAPON SUMMON</span><h2>星の向こうから、届く一本。</h2><p>にゃんるなの杖、つきねこの銃、オムソロの光剣。<br>★2〜★4は各キャラ・各レア度に3種類。27本の中から、どの一本に出会えるだろう。</p></div>
 <section class="weapon-summon" aria-label="専用武器ガチャ"><div class="summon-emblem">${icon('star')}</div><span class="eyebrow">THREE FRIENDS · ONE TICKET</span><h3>専用武器ガチャ</h3><p>★2以上の武器が、いずれかのキャラに1本。</p><div class="weapon-ticket-wallet">${icon('spark')}<span>専用武器ガチャ券<strong id="weapon-ticket-count">${tickets.toLocaleString()}<small>枚</small></strong></span></div><button class="primary" data-draw-weapon ${tickets<1?'disabled':''}>${icon('star')}<span>${tickets>0?'ガチャを1回まわす':'ガチャ券がありません'}<small>専用武器ガチャ券 ×1 を使用</small></span>${icon('arrow')}</button><p class="ticket-source">全章の通常ボス・強ボスを倒すと、1体ごとに${WEAPON_TICKET_DROP_RATE*100}%で1枚入手。<br>ドロップした券はすぐに保存され、途中帰還・敗北でも持ち帰れます。</p></section>
 ${last?`<section class="last-weapon-draw"><small>前回の結果 · ${profile.weapons.draws}回目</small><strong>${heroName(last.heroId)}専用 · ${last.weapon.name}</strong>${weaponRarityBadge(last.rarity)}<span>${profile.weapons.lastDraw.duplicate?`重複 → 星の芽 ×${last.rarity.duplicateBuds}`:'新しい武器を獲得'}</span></section>`:''}
 <details class="weapon-odds"><summary>提供割合・重複時の内容を見る</summary><p>キャラは3人から均等に抽選（各1/3）。レア度を決め、その中の武器3種類から均等に抽選します。編成・加入状況・所持武器によって確率は変わりません。</p><table><thead><tr><th>レア度</th><th>合計</th><th>各武器1本</th><th>重複時</th></tr></thead><tbody>${WEAPON_RARITIES.filter(r=>r.chance).map(r=>`<tr><th>${rarityLabel(r)}</th><td>${r.chance*100}%</td><td>約${(r.chance*100/9).toFixed(4)}%</td><td>星の芽 ×${r.duplicateBuds}</td></tr>`).join('')}</tbody></table><p>各武器の確率は小数点以下を丸めています。★1は初期装備のため抽選に含まれません。所持済みの「同じ武器・同じレア度」だけを星の芽へ変換。別の武器なら同じキャラ・レア度でも新規獲得です。未加入キャラの武器も保管され、加入後に使用できます。</p></details>
 <div class="weapon-collection-heading"><h3>専用武器コレクション</h3><p>各キャラ10本。獲得した武器は「装備」で自由に付け替え。<br>ガチャでは装備を変更しません。ユニーク装備は別の1枠です。</p></div><div class="weapon-collection">${HEROES.map(hero=>{const item=equippedWeapon(profile,hero.id),unlocked=isHeroUnlocked(profile,hero.id),count=WEAPON_CATALOG.filter(w=>w.heroId===hero.id&&profile.weapons.owned.includes(w.id)).length;return `<article class="weapon-collection-card" data-weapon-hero="${hero.id}" style="--rarity-color:${item.rarity.color}"><header><span class="portrait ${hero.id}"></span><div><h4>${hero.name}</h4><small>${unlocked?'現在の装備':'加入まで保管'} · ${count} / 10本所持</small></div></header><img src="${weaponImage(item)}" alt="${item.weapon.name}" width="256" height="256" decoding="async">${weaponRarityBadge(item.rarity)}<h4>${item.weapon.name}</h4><p>${weaponBonusText(item)}</p>${!unlocked?`<p class="weapon-unlock-note">${recruitmentNote(hero.id)}</p>`:`<button class="secondary" data-open-equipment="${hero.id}">武器を選んで付け替える →</button>`}</article>`;}).join('')}</div>`;
}
export function weaponDrawResult(result,profile,storageAvailable){
 const {item,duplicate,duplicateBuds}=result,unlocked=isHeroUnlocked(profile,item.heroId),selected=equippedWeapon(profile,item.heroId).id===item.id;
 return `<section id="weapon-draw-result" class="weapon-draw-result" style="--rarity-color:${item.rarity.color}"><span class="eyebrow">${duplicate?'DUPLICATE REWARD':'NEW WEAPON'}</span><h2>${duplicate?'武器の力を、育成へ。':'新しい専用武器を獲得！'}</h2><div class="draw-weapon-art"><img src="${weaponImage(item)}" alt="${item.weapon.name}" width="256" height="256"></div>${weaponRarityBadge(item.rarity)}<p class="draw-hero"><span class="portrait ${item.heroId}"></span>${heroName(item.heroId)}専用</p><h3>${item.weapon.name}</h3><p>${weaponBonusText(item)}<br>${item.weapon.note}</p><div class="draw-outcome">${duplicate?`所持済みのため 星の芽 <b>+${duplicateBuds}</b>`:!unlocked?'加入後に使えるよう保管しました':'コレクションに追加しました。装備は変更していません。'}</div><p class="draw-saved">残り ${profile.inventory.weaponTicket}枚 · ${storageAvailable?'結果を保存しました':'この環境では保存できません'}</p>${unlocked?`<button class="secondary draw-equip" data-equip-weapon="${item.id}" data-weapon-hero="${item.heroId}" ${selected?'disabled':''}>${selected?'✓ この武器を装備中':'この武器を装備する'}</button>`:''}<button class="primary" data-close>結果を閉じる ${icon('check')}</button></section>`;
}
