import {HEROES} from './model.js';
import {equipmentImage} from './equipment.js';
import {isHeroUnlocked,recruitmentNote} from './recruitment.js';
import {WEAPON_RARITIES,WEAPON_TICKET_DROP_RATE,equippedWeapon,weaponVariant,rarityLabel} from './weapons.js';
import {icon} from './icons.js';

export const weaponBonusText=rarity=>rarity.attack?`攻撃力 +${Math.round(rarity.attack*100)}%`:'初期装備 · 威力補正なし';
export const weaponRarityBadge=rarity=>`<span class="weapon-rarity" style="--rarity-color:${rarity.color}">${rarityLabel(rarity)}</span>`;
const heroName=id=>HEROES.find(h=>h.id===id).name;
export function weaponGachaView(profile){
 const tickets=profile.inventory.weaponTicket,last=weaponVariant(profile.weapons.lastDraw?.weaponId);
 return `<div class="rewards-intro"><span class="eyebrow">SIGNATURE WEAPON SUMMON</span><h2>星の向こうから、届く一本。</h2><p>にゃんるなの杖、つきねこの銃、オムソロの光剣。<br>どの仲間の専用武器が届くかは、開けてからのお楽しみ。</p></div>
 <section class="weapon-summon" aria-label="専用武器ガチャ"><div class="summon-emblem">${icon('star')}</div><span class="eyebrow">THREE FRIENDS · ONE TICKET</span><h3>専用武器ガチャ</h3><p>★2以上の武器が、いずれかのキャラに1本。</p><div class="weapon-ticket-wallet">${icon('spark')}<span>専用武器ガチャ券<strong id="weapon-ticket-count">${tickets.toLocaleString()}<small>枚</small></strong></span></div><button class="primary" data-draw-weapon ${tickets<1?'disabled':''}>${icon('star')}<span>${tickets>0?'ガチャを1回まわす':'ガチャ券がありません'}<small>専用武器ガチャ券 ×1 を使用</small></span>${icon('arrow')}</button><p class="ticket-source">全章の通常ボス・強ボスを倒すと、1体ごとに${WEAPON_TICKET_DROP_RATE*100}%で1枚入手。<br>ドロップした券はすぐに保存され、途中帰還・敗北でも持ち帰れます。</p></section>
 ${last?`<section class="last-weapon-draw"><small>前回の結果 · ${profile.weapons.draws}回目</small><strong>${heroName(last.heroId)}専用 · ${last.weapon.name}</strong>${weaponRarityBadge(last.rarity)}<span>${profile.weapons.lastDraw.duplicate?`重複 → 星の芽 ×${last.rarity.duplicateBuds}`:'新しい武器を獲得'}</span></section>`:''}
 <details class="weapon-odds"><summary>提供割合・重複時の内容を見る</summary><p>キャラは3人から均等に抽選（各1/3）。選択中のキャラ・編成・加入状況・所持武器によって確率は変わりません。</p><table><thead><tr><th>レア度</th><th>合計</th><th>各キャラの武器</th><th>重複時</th></tr></thead><tbody>${WEAPON_RARITIES.filter(r=>r.chance).map(r=>`<tr><th>${rarityLabel(r)}</th><td>${r.chance*100}%</td><td>${r.rank===2?'25%':`約${(r.chance*100/3).toFixed(2)}%`}</td><td>星の芽 ×${r.duplicateBuds}</td></tr>`).join('')}</tbody></table><p>各キャラの表示確率は小数点以下を丸めています。★1は初期装備のため抽選に含まれません。所持済みの「同じキャラ・同じレア度」の武器は星の芽へ変換。未加入キャラの武器も保管され、加入後に使用できます。</p></details>
 <div class="weapon-collection-heading"><h3>専用武器コレクション</h3><p>武器種はキャラごとに固定。所持する最高レア度を自動装備します。<br>通常攻撃・攻撃スキルの威力に反映。ユニーク装備は別の1枠です。</p></div><div class="weapon-collection">${HEROES.map(hero=>{const item=equippedWeapon(profile,hero.id),unlocked=isHeroUnlocked(profile,hero.id);return `<article class="weapon-collection-card" data-weapon-hero="${hero.id}" style="--rarity-color:${item.rarity.color}"><header><span class="portrait ${hero.id}"></span><div><h4>${hero.name}</h4><small>${unlocked?'所持最高レアを装備中':'加入まで保管'}</small></div></header><img src="${equipmentImage(item.weapon.id)}" alt="${item.weapon.name}" width="256" height="256" decoding="async">${weaponRarityBadge(item.rarity)}<h4>${item.weapon.name}</h4><p>${weaponBonusText(item.rarity)}</p><div class="weapon-rank-collection">${WEAPON_RARITIES.map(r=>{const owned=profile.weapons.owned.includes(`${item.weapon.id}-r${r.rank}`);return `<span class="${owned?'owned':''}" title="${rarityLabel(r)} ${owned?'所持済み':'未所持'}">★${r.rank}<small>${owned?'所持':'未所持'}</small></span>`;}).join('')}</div>${!unlocked?`<p class="weapon-unlock-note">${recruitmentNote(hero.id)}</p>`:`<button class="secondary" data-open-equipment="${hero.id}">装備と能力を確認する →</button>`}</article>`;}).join('')}</div>`;
}
export function weaponDrawResult(result,profile,storageAvailable){
 const {item,duplicate,duplicateBuds,upgraded}=result,unlocked=isHeroUnlocked(profile,item.heroId);
 return `<section id="weapon-draw-result" class="weapon-draw-result" style="--rarity-color:${item.rarity.color}"><span class="eyebrow">${duplicate?'DUPLICATE REWARD':'NEW WEAPON'}</span><h2>${duplicate?'武器の力を、育成へ。':'新しい専用武器を獲得！'}</h2><div class="draw-weapon-art"><img src="${equipmentImage(item.weapon.id)}" alt="${item.weapon.name}" width="256" height="256"></div>${weaponRarityBadge(item.rarity)}<p class="draw-hero"><span class="portrait ${item.heroId}"></span>${heroName(item.heroId)}専用</p><h3>${item.weapon.name}</h3><p>${weaponBonusText(item.rarity)}</p><div class="draw-outcome">${duplicate?`所持済みのため 星の芽 <b>+${duplicateBuds}</b>`:upgraded?unlocked?'最高レア度を自動装備しました':'加入後に使えるよう保管しました':'コレクションに追加。より高いレア度の装備を継続します。'}</div><p class="draw-saved">残り ${profile.inventory.weaponTicket}枚 · ${storageAvailable?'結果を保存しました':'この環境では保存できません'}</p><button class="primary" data-close>結果を閉じる ${icon('check')}</button></section>`;
}
